[package]
name = "little-cdn"
version = "0.1.0"
edition = "2021"
authors = ["ponurakk"]
license = "MIT"
publish = false

[workspace]
members = [".", "api", "cmd"]

[dependencies]
little-cdn-cmd = { path = "cmd" }
