[package]
name = "little-cdn-cmd"
version = "0.1.0"
edition = "2021"
authors = ["ponurakk"]
license = "MIT"
publish = false

[dependencies]
little-cdn-api = { path = "../api" }

clap = { version = "4.0.19", features = ["derive", "cargo"] }
colored = "2.0.0"